### ISSUE TITLE
locationName not working

### ISSUE THREAD

**Issue by arnaubennassar** [MacTheZazou/paper-input-location#1]
locationName was not working for me. I managed to solve it by handling the event 'place-changed'. However I've had also to change your code. Just put the line "this.fire('place-changed');" from the function "_onChangePlace"at the bottom of the function, and bum! working!

Nice element, good job!

**Comment by MacTheZazou** [comment]
Thank you!

will manage that bug in 3-4 days!

**Comment by MacTheZazou** [comment]
@arnaubennassar With this update (v2.0.0), everything should work better with the event. Thank you for your contribution!

I had to change the event name.
