### ISSUE TITLE
paper-input is created disabled

### ISSUE THREAD

**Issue by josealbertoflores** [MacTheZazou/paper-input-location#2]
After adding the paper-input-location element, the internal paper-input appears with the disabled attribute by default. If I remove that attribute using the dev tools, the paper-input is enabled and the autocomplete works normally with google api.

**Comment by MacTheZazou** [comment]
Will check that tonight or tommorow. Thank you for the issue.

**Comment by MacTheZazou** [comment]
@josefloreschura With this update (v2.0.0) The problem should be solved.

**Comment by josealbertoflores** [comment]
Tested and verified is fixed. Thanks a lot!
